augment_train_set: false
batch_size: 256
dataset_to_use: RGD1
epochs: 500
folder_name: RGD1_Model_trained_with_RMSD_and_DMAE
hidden_features: 64
include_context: null
learning_rate_scheduler: false
lr: 0.0005
model_name: RGD1_Model_trained_with_RMSD_and_DMAE
n_layers: 8
noise_schedule: sigmoid_2
random_rotations: false
remove_hydrogens: false
remove_product: false
test_sampling_number: 10
timesteps: 1000
train_or_test: train
use_graph_in_model: false
use_mse_loss: true
wandb_project_name: RGD1_Model_trained_with_RMSD_and_DMAE
