# Training
train_test: train

# Use Graph or Not: 
use_graph_in_model: False


# Use MSE in loss: 
use_mse: False

# Diffusion Variables
dataset_to_use: RDKIT
timesteps: 1_000
noise_schedule: sigmoid_2
remove_hydrogens: False
random_rotations: False
augment_train_set: True
include_context: 
remove_product: False



# Training Variables: 
lr: 0.0005
epochs: 1_000
batch_size: 128
learning_rate_scheduler: False 
model_name: RDKIT_dataset_dmae
folder_name: RDKIT_dataset_dmae


wandb_project_name: RDKIT_dataset_3000

# Model Variables: 
n_layers: 8
hidden_features: 64 

test_sampling_number: 10


