dataset_to_use: W93
timesteps: 5_000
noise_schedule: sigmoid_2
loss_type: l2
remove_hydrogens: False
random_rotations: False
augment_train_set: True
include_context: False

train_test: train

lr: 0.0001
epochs: 2000
batch_size: 64
learning_rate_scheduler: False 
automatic_model_name: True
model_save_path: None
folder_name: None

wandb_project_name: Diffusion_5_layer_2000_timesteps

out_node: 3
context_nf: 0
n_dims: 3
n_layers: 8
hidden_features: 64 

save_samples: True
test_sampling_number: 10