# Testing
train_test: test

# Use Graph or Not: 
use_graph_in_model: False


# Diffusion Variables
dataset_to_use: TX1
timesteps: 2_000
noise_schedule: sigmoid_2
remove_hydrogens: False
random_rotations: False
augment_train_set: False
include_context: False
remove_product: False



# Training Variables: 
lr: 0.0001
epochs: 10
batch_size: 64
learning_rate_scheduler: False 
model_name: cool_TS_Diffusion_model 
folder_name: pre_trained_diffusion_simple/


wandb_project_name: Diffusion_TEST_123

# Model Variables: 
n_layers: 8
hidden_features: 64 

# Testing Variable: 
test_sampling_number: 10