# Testing
train_test: test

# Use Graph or Not: 
use_graph_in_model: True


# Diffusion Variables
dataset_to_use: W93
timesteps: 5_000
noise_schedule: sigmoid_2
loss_type: l2
remove_hydrogens: False
random_rotations: False
augment_train_set: True
include_context: False
remove_product: False



# Training Variables: 
lr: 0.0001
epochs: 10
batch_size: 64
learning_rate_scheduler: False 
model_name: cool_TS_Diffusion_model 
folder_name: small_graph_diffusion


wandb_project_name: Diffusion_TEST_123

# Model Variables: 
n_layers: 2
hidden_features: 64 

# Testing Variable: 
test_sampling_number: 10