# Training
train_test: train

# Use Graph or Not: 
use_graph_in_model: False

# Use MSE in loss: 
use_mse: False


# Diffusion Variables
dataset_to_use: W93
timesteps: 1_000
noise_schedule: sigmoid_2
remove_hydrogens: False
random_rotations: False
augment_train_set: True
include_context: 
remove_product: False



# Training Variables: 
lr: 0.0002
epochs: 3000
batch_size: 64
learning_rate_scheduler: False 
model_name: Testing_Diffusion_Model_with_DMAE_loss_operation_and_mse_3000_epochs_padding_fixed
folder_name: Model_with_DMAE_loss_each_sample_of_bactch_and_mse_3000_epochs_padding_fixed


wandb_project_name: Diff_with_MAE_loss

# Model Variables: 
n_layers: 6
hidden_features: 64 


test_sampling_number: 10


