# Training
train_test: train

# Use Graph or Not: 
use_graph_in_model: True


# Diffusion Variables
dataset_to_use: W93
timesteps: 1_000
noise_schedule: sigmoid_2
remove_hydrogens: False
random_rotations: False
augment_train_set: True
include_context: False
remove_product: False



# Training Variables: 
lr: 0.0001
epochs: 2
batch_size: 64
learning_rate_scheduler: False 
model_name: cool_Diffusion_model 
folder_name: Example_Name


wandb_project_name: Diffusion_TEST_123

# Model Variables: 
n_layers: 1
hidden_features: 64 



