name: Environment Maker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  environment:
    name: Environment Maker for Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: diff_sach
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false

      - name: Display Conda info and list
        run: |
          conda info
          conda list

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
